# Magister en Cs. Mención Computación

## ¿Cómo me meto al magister?

Independiente de si haces doble titulación (Explicaremos más adelante qué clase de brujería es esta) o primero terminas la ingeniería, hay varias cosas que son iguales en ambos casos. Por ejemplo, si te metes al magíster viniendo desde el DCC te convalidan todos los ramos. Bueno, casi, lo único extra que hay que tomar es CC71T - Investigación en Cs.de la Computación.(Métodos, Técnicas, Perspectivas)[3]. Aunque también muchos toman este ramo como electivo en pregrado y por lo tanto cuando entran al magíster no tienen que tomar ningún ramo adicional.

La postulación al magister también es independiente de si haces o no doble titulación. Puedes postular tanto con la licenciatura o con el título. La forma más fácil es hacerlo con la licenciatura (y la única si haces doble titulación). Tramitar la licenciatura es un trámite bien sencillo, primero debes tener todos los ramos aprobados, luego pagar 25 lucas en ese rincón que está en el hall sur (Unidad de Aranceles) y después avisar en la secretaría de estudios (Torre Central, 1er. piso) que pagaste, porque ellos no se dan cuenta solos a pesar de que esté toda la información en el sistema. De ahí en adelante deberás seguir en Ucampus / Títulos y Grados tu proceso de licenciatura e ir a molestar a las áreas que se demoren en tenerte los ticket listos. La resolución puede tardar un poco, entre un par de semanas, hasta un mes, así que hay que estar atento para hacer el trámite el semestre antes de que empieces el magister. De todas formas, la entrega del Diploma puede tomar bastante tiempo (entre 2 y 5 meses), porque el Rector no lo firma nunca, pero no te preocupes pues debería bastar con que internamente figures como licenciado. Si tienes problemas porque no te están contando un ramo que sí debería contar, debes pimponearte entre Angélica y la secretaría de estudios hasta que agreguen el ramo al plan de estudios.

La postulación al magister debes hacerla el semestre anterior al que entras (thanks captain) y puede hacerse tanto en otoño como primavera. Si la haces en primavera (para otoño del año siguiente), intenta hablar con Angélica (con un correo basta) para informarle de tu interés en seguir con magíster antes de mediados de septiembre. El trámite de matrícula es muy sencillo por ser alguien que viene de la misma escuela. Los documentos necesarios cambian todos los años, pero tienes que llevar cosas como la fotocopia legalizada del Diploma de licenciatura, o una carta de motivación. Por venir del mismo departamento nos piden muy pocas cosas, pero el semestre en que postules debes preguntar directamente a Angélica y tratar de pelear por llevar la menos cantidad de cosas posibles. Como ejemplo, en el semestre de primavera 2017 (postulando para otoño 2018) nos pidieron solamente el currículum (algunos usamos el mismo de las prácticas) y una carta a Nancy comprometiéndonos con entregarle el diploma de licenciatura apenas lo tuviéramos.

Al igual que la de cualquier persona tu postulación tiene que ser revisada y aceptada, pero como vienes del mismo departamento la ven y dicen “ah este cabro obvio que se puede el magíster porque estudio en Beauchef y todos los que estudian en Beauchef son secos y el resto son puros giles", así que no te preocupes por eso.
